### ISSUE TITLE
GO button active at wrong time

### ISSUE THREAD

**Issue by astronomerdave** [CaltechOpticalObservatories/NGPS#10]
The state is IDLE and the GO button is green and clickable when there are no targets:
![image](https://github.com/CaltechOpticalObservatories/NGPS/assets/3028392/f87adc6e-ff73-484a-a6aa-0fd03558c321)

Per design, state should be "No Targets" and GO button should be greyed-out:
![image](https://github.com/CaltechOpticalObservatories/NGPS/assets/3028392/50a5500f-ba5b-46db-8557-88c09bba6b9e)

**Comment by jenniferwillow** [comment]
This was rather complicated to do but it's been finished.  When I get a READY state I check if the main table has targets in it (i.e. row count not equal 0) If the table has no targets I set the STATE of the observation sequencer (internal) to be READY_NO_TARGET which changes the GUI to the NO Targets state.  When you either open or import a target list it makes sure that there are targets in the list and then changes the OS state to READY again.  I think there are only 2 ways to have non-zero row count: (1) import a target list, (2) open a target list from the database.  If this is true then this issue should be closed.
