### ISSUE TITLE
completed targets are hard to read when selected

### ISSUE THREAD

**Issue by astronomerdave** [CaltechOpticalObservatories/NGPS#11]
White on yellow text is difficult to read.
![image](https://github.com/CaltechOpticalObservatories/NGPS/assets/3028392/349a1646-fb5a-482d-a824-6b816d59f6d8)

**Comment by chazshapiro** [comment]
See constructTable() in NGPSFrame.java

**Comment by chazshapiro** [comment]
Fixed
<img width="378" alt="Screenshot 2024-08-22 at 9 59 37 AM" src="https://github.com/user-attachments/assets/ed8b63a0-d8fe-45ed-8562-d96f2e2a1daa">
