### ISSUE TITLE
Strange GUI behavior on importing sample_input_1.csv

### ISSUE THREAD

**Issue by cfremling** [CaltechOpticalObservatories/NGPS#116]
Several large time blocks generated from one target in the timeline. Mismatch between selected target in the target list editor window and the timeline plot.

<img width="1747" alt="Screen Shot 2024-09-12 at 11 07 25 AM" src="https://github.com/user-attachments/assets/d775e766-4bb0-417c-b6f9-f4b1222cc81c">

**Comment by chazshapiro** [comment]
EGAD.  It's something to do with the timestamp -- all of the weird targets have exposure start or end times of 12:xxx but they are appearing as 00:xxx

**Comment by chazshapiro** [comment]
It goes away when I hit accept again

**Comment by chazshapiro** [comment]
Fixed in ImportFrame.java by @jenniferwillow

**Comment by chazshapiro** [comment]
Never mind -- the issue depends on the start date/time.  I think it involves having targets that are observed between 12:00 and 13:00

**Comment by chazshapiro** [comment]
Fixed (but not yet committed) in OTMlauncher.java
