### ISSUE TITLE
aborted target remains active

### ISSUE THREAD

**Issue by astronomerdave** [CaltechOpticalObservatories/NGPS#12]
After clicking "Abort" the target remains flagged as active.
![image](https://github.com/CaltechOpticalObservatories/NGPS/assets/3028392/f8f2cace-1fe8-46ae-a2a5-07e0717063a3)

**Comment by jenniferwillow** [comment]
What behavior would you like?  Recall that I don't change the state variable, you do.  You change the target to active, then to completed.  If I send the cancel, shouldn't the OS then mark the target as completed or change it back to pending.  I initially set all of the targets to pending when the list is imported but I never change this after creating it.

**Comment by astronomerdave** [comment]
I think you are correct, that the sequencer should change the target state; I will look into this.

**Comment by astronomerdave** [comment]
Found and fixed sequencer bug where an abort did not always necessarily update the target state.
If the sequencer is running or paused, an abort will update the target state to "**inactive**".
