### ISSUE TITLE
Observe GUI can crash if sequencerd is restarted

### ISSUE THREAD

**Issue by astronomerdave** [CaltechOpticalObservatories/NGPS#120]
Not every time, but I can crash the GUI if I restart the daemons while the GUI is running. This is running the desktop-icon version (not the -devel version). To reproduce, run the GUI, then from the command line,
```
ngps kill
ngps start
```

which will restart all daemons. Sometimes this will cause the GUI to complain about not being able to connect. While checking to see if it was repeatable, the GUI got to a state where it is frozen and I can't click on anything.

**Comment by chazshapiro** [comment]
java issue only
