### ISSUE TITLE
Unclear why some objects only included in the plan after a big time gap

### ISSUE THREAD

**Issue by kaustavkdas** [CaltechOpticalObservatories/NGPS#123]
see attached screenshot 

<img width="477" alt="Screenshot 2024-09-25 at 11 03 44 PM" src="https://github.com/user-attachments/assets/631bcabd-bb19-4083-99ee-7c85fc8f780d">

**Comment by chazshapiro** [comment]
user needs to check OTMflag to see reason for delay
