### ISSUE TITLE
very important: need some level of priority based scheduling

### ISSUE THREAD

**Issue by kaustavkdas** [CaltechOpticalObservatories/NGPS#124]
Based on discussion with other observers on when the scheduler will be helpful:

Currently the schedule is only based on the order in the input table? This means high priority targets at the end of the table are left out!!

Please add a 1-0 binary bit for whether a target is visible and satisfies the user-specified airmass constraints (with sensible default)

For targets that are visible, please add a column for priority to break the tie and set the order of observations.

We can worry about the next level of optimization later.

**Comment by chazshapiro** [comment]
Out of scope
