### ISSUE TITLE
GUI: Add popup window showing airmass plot for 1 target

### ISSUE THREAD

**Issue by chazshapiro** [CaltechOpticalObservatories/NGPS#128]

**Comment by chazshapiro** [comment]
I'd like to just popup this handy website for the selected target:

https://airmass.org/chart/obsid:palomar/date:2024-10-03/object:ngps-target/ra:240.0/dec:45.0#dailyheading

 ...but the website doesn't seem to work from Firefox on our machine.

**Comment by astronomerdave** [comment]
> but the website doesn't seem to work from Firefox on our machine.

It does now.

**Comment by chazshapiro** [comment]
Added in commit 986b2fc77dc3bc617ad10fbe0756e5c0e1a4145d

**Comment by chazshapiro** [comment]
@astronomerdave Firefox needs to be updated on deployed computer, then we can close this

**Comment by astronomerdave** [comment]
> Firefox needs to be updated on deployed computer, then we can close this

done
