### ISSUE TITLE
GUI: Change NOTES column to PRIORITY

### ISSUE THREAD

**Issue by chazshapiro** [CaltechOpticalObservatories/NGPS#129]

**Comment by chazshapiro** [comment]
Can column be colored?

**Comment by astronomerdave** [comment]
Or "Observer's Priority" to allow having the word "priority" while distinguishing it from an instrument/software priority.

**Comment by chazshapiro** [comment]
done in commit 7e0462ef60951f25987f100dcd11b564164d8a63
