### ISSUE TITLE
Get Target from Database

### ISSUE THREAD

**Issue by astronomerdave** [CaltechOpticalObservatories/NGPS#13]
Is this menu option supposed to work?
![image](https://github.com/CaltechOpticalObservatories/NGPS/assets/3028392/c832ef5c-26c9-45fd-b6be-97dbe4dcd5ef)

**Comment by jenniferwillow** [comment]
Yes, this works.  Select a target name in one of the lists that you own and press the search button.  The database will be searched and if the target exists it will show up in the table.  The table then allows you to select a target and then copy it so you can put it in your active table.
<img width="640" alt="image" src="https://github.com/CaltechOpticalObservatories/NGPS/assets/21295144/72750345-279d-40b4-9a02-3e127ae302ad">
