### ISSUE TITLE
"X" close OTM output will kill ngps-observe

### ISSUE THREAD

**Issue by astronomerdave** [CaltechOpticalObservatories/NGPS#14]
If you view the OTM output and click the "X" button then all of ngps-observe will quit.
Clicking the "OK" button will close the OTM output cleanly, however.
![image](https://github.com/CaltechOpticalObservatories/NGPS/assets/3028392/28e1dc7f-ab73-4747-8b2e-b92efd1c8756)

**Comment by jenniferwillow** [comment]
I have added a call to the JFrame.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE) so that the dialog closes but doesn't close the program.
