### ISSUE TITLE
ACAM/Slicecam GUI temperature controls?

### ISSUE THREAD

**Issue by astronomerdave** [CaltechOpticalObservatories/NGPS#147]
The Andors need to have their cooling turned on. This is currently done through the command line. The Sequencer could turn on the cooling as part of the startup, but does it need to monitor it? Is there an optimal temperature? Should there be a monitor and/or control via the GUI?

**Comment by chazshapiro** [comment]
At least get the cooling status and put it in the acam/slitv headers as a bool.  I think if they overheat they just shut down.  I wouldn't set up any kind of monitoring unless we find that it's a problem.  If there's a default temperature that's probably fine.

**Comment by chazshapiro** [comment]
We could also put temperatures in one of the databases - that's a good enough "monitor"

**Comment by chazshapiro** [comment]
We currently write temperatures to the database and the headers

**Comment by astronomerdave** [comment]
We do write temperature; this issue was about control. There is currently only sequencer and CLI for control. What if something happens and it is off?

**Comment by chazshapiro** [comment]
Cameras should cool by default, and if cooling is off, there just needs to be an alert of some kind to restart.  So maybe a restart button not a temperature button.  And you could add cooling to the status message?

**Comment by astronomerdave** [comment]
When operated by the sequencer, the sequencer turns on cooling.
