### ISSUE TITLE
target name change in detail window not reflected in table

### ISSUE THREAD

**Issue by astronomerdave** [CaltechOpticalObservatories/NGPS#15]
![image](https://github.com/CaltechOpticalObservatories/NGPS/assets/3028392/13e50066-6e24-48fc-af9a-2a496c11f032)

**Comment by jenniferwillow** [comment]
The action that causes the update is to select the row.  As soon as you select the row it updates.  This is feature of how the system works not a bug

**Comment by astronomerdave** [comment]
Could you please double-check this? I understand one must click to force the change to be shown, but I have clicked and cannot get the target name to change.

**Comment by jenniferwillow** [comment]
Could you jump on Zoom for a minute?  I want to go thru this with you.
Jennifer

On May 24, 2023, at 11:46 AM, David Hale ***@***.******@***.***>> wrote:



Could you please double-check this? I understand one must click to force the change to be shown, but I have clicked and cannot get the target name to change.

**Comment by jenniferwillow** [comment]
Dave, why did you ignore the zoom request before reopening this case?

**Comment by astronomerdave** [comment]
> Dave, why did you ignore the zoom request before reopening this case?

Did not immediately see zoom request; github issue tracking is not the most efficient method of communication.

**Comment by jenniferwillow** [comment]
The target name in the details tabbed pane is no longer editable.  You can only edit the target name in the table.
