### ISSUE TITLE
target info not saved to database

### ISSUE THREAD

**Issue by astronomerdave** [CaltechOpticalObservatories/NGPS#151]
Steps to re-create:

1. loaded a target list from my account which had one target with coords 0:0:0 0:0:0
2. changed coords to something non-zero
3. clicked accept (according to the manual, this should save my target to the database)
4. issued command-line test commands to mimic what the sequencer would do:
`seq targetset bob` (selects the target set)
`seq test getnext` (loads the first target in the set with state=PENDING, which is what the sequencer will do when told to start.
5. Notice in the message pane says the target coords are 0 0

![image](https://github.com/user-attachments/assets/b1e814a3-c03d-4be0-b607-0e19899a3b37)

It might be worth noting there is a discrepancy in the target ID numbers. When I issued seq targetset bob from the command line, it reported as having loaded target set ID 182, but as you can see in the GUI, it is ID 183.

![image](https://github.com/user-attachments/assets/4f23646a-45bf-46ac-96a6-85df08351c3a)

**Comment by astronomerdave** [comment]
I next marked my target as completed, again from the command line, seq test complete, which performs the actions that the sequencer would do after an observation completed, which is to change the state to COMPLETED and insert it into the completed targets table. Note the owner is cshapiro even though I am logged in as dhale.

![image](https://github.com/user-attachments/assets/8eec086f-b9c6-4db3-a191-8129c9fb7737)

**Comment by astronomerdave** [comment]
This might just be a glitch in how targetset bob was created, because still logged in as dhale I created a new targetlist from scratch, and then followed the same steps above. The target was correctly loaded and when added to the completed table, is identified as me being the owner.

![image](https://github.com/user-attachments/assets/4b83987b-a849-4f1c-a271-0139c53ffb2a)

**Comment by chazshapiro** [comment]
java issue only
