### ISSUE TITLE
thermald:  native "set" commands not working

### ISSUE THREAD

**Issue by chazshapiro** [CaltechOpticalObservatories/NGPS#164]
A query type command works
`$ thermal native 1 RANGE? 1`
`0 DONE`

Not working:
`$ thermal native 1 RANGE 1 3`
`ERROR`

`$ thermal native 1 RANGE 1, 3`
`ERROR`

**Comment by astronomerdave** [comment]
fixed in commit 1e719d9b0d051d22c43ff9a0a06d375c566c02c7
