### ISSUE TITLE
Faster CCD waveforms version for testing

### ISSUE THREAD

**Issue by chazshapiro** [CaltechOpticalObservatories/NGPS#175]
Some extra speed will be useful for getting tests set up

**Comment by astronomerdave** [comment]
re-prioritized in discussion with Roger/Chaz/Dave as:

1. spatial binning
2. multiple BOIs
3. single BOI
4. faster pixel time

(1) already exists
(3) sort-of exists -- you can't pick any arbitrary BOI but you can specify the number of rows to read.

**Comment by astronomerdave** [comment]
This is current result of specifying readout of only 510, instead of 1020 rows (R at left, I at right):
![image](https://github.com/user-attachments/assets/c0a774bb-6133-4ec9-8090-0c7764b43f88)

**Comment by astronomerdave** [comment]
2 and 3 now implemented in commit f414ed65871d75d339f5cdfdb63f9f241f2277c7
Any arbitrary size and number (up to 10) of BOIs can be specified.
