### ISSUE TITLE
ACAM GAIN keyword

### ISSUE THREAD

**Issue by astronomerdave** [CaltechOpticalObservatories/NGPS#185]
Update existing keyword `GAIN=1` to `GAIN=0.71` but only when `CCDGAIN=1`. Remove keyword when CCDGAIN is not 1.

**Comment by chazshapiro** [comment]
When CCDGAIN is not 1:

GAIN_1 = 0.71 [e-/ADU]

GAIN = ( 0.191*CCDGAIN+0.189 ) * GAIN_1

**Comment by astronomerdave** [comment]
This can't be true for any clocking speed, can it?

**Comment by astronomerdave** [comment]
implemented in commit 10c1a86d384b4c0a6a17283789bc8d18ed8968c8
