### ISSUE TITLE
Add display of expected guider field for given pointing/PA

### ISSUE THREAD

**Issue by MateuszKM** [CaltechOpticalObservatories/NGPS#198]

**Comment by astronomerdave** [comment]
I think this is built in to ds9 already, right?

**Comment by chazshapiro** [comment]
You can currently get it on a grabbed frame.  Is that enough?  Overlaying it on the live feed will take some effort.

**Comment by chazshapiro** [comment]
<img width="1328" alt="Screenshot 2024-11-19 at 9 04 34 AM" src="https://github.com/user-attachments/assets/2e5a9fe7-d8df-47b3-98af-5471d0e65ee9">

**Comment by astronomerdave** [comment]
What's the use case? Maybe a grabbed frame is sufficient?

**Comment by chazshapiro** [comment]
Also, there will always be an offset due to TCS errors, which **will** confuse people, so I am closing this until the idea is better baked.
