### ISSUE TITLE
Slicecam produces two frames frome the same camera

### ISSUE THREAD

**Issue by MateuszKM** [CaltechOpticalObservatories/NGPS#199]

**Comment by astronomerdave** [comment]
Possibly a driver issue; Andor is looking into this.

**Comment by astronomerdave** [comment]
resolved in commit 0fe0fc5143bf17d92dd58d06341515e6e3479d0b

**Comment by astronomerdave** [comment]
On closer examination, this might not be completely resolved. I saved 1027 frames over a period of 15 minutes (`/data/slicecam/20241127`). It was found that `slicecam_00077.fits` did not contain duplicates from the same camera, but contains two _unique_ frames from the same camera -- two separate exposures.

For illustration, here is a correct image, slicecam_00076:
![image](https://github.com/user-attachments/assets/ba3d664d-9d9b-42dc-bf67-a4ae05e3b4ec)

and here is the following image, slicecam_00077:
![image](https://github.com/user-attachments/assets/45a56632-04a4-4c0c-b6a2-d8a2a290f7cc)
At first glance it might look like a duplicate but they are not 100% identical, therefore must be two distinct exposures, but are clearly from the R (right-side) camera.


This seems to have happened in several files, at least these:
```
['slicecam_00565.fits',
 'slicecam_00983.fits',
 'slicecam_00982.fits',
 'slicecam_00076.fits',
 'slicecam_00286.fits',
 'slicecam_00146.fits',
 'slicecam_00705.fits',
 'slicecam_00775.fits',
 'slicecam_00635.fits']
```

**Comment by astronomerdave** [comment]
resolved for real (not committed yet)
