### ISSUE TITLE
Account for spatial binning in ACAM WCS headers

### ISSUE THREAD

**Issue by chazshapiro** [CaltechOpticalObservatories/NGPS#203]
Like the title says...

**Comment by astronomerdave** [comment]
@chazshapiro is this working correctly for slicecam?

**Comment by chazshapiro** [comment]
PIXSCALE is not correct.  It should get multiplied by the bin factor (assumes box axes are the same binning)

**Comment by chazshapiro** [comment]
Other SCAM headers look OK

**Comment by chazshapiro** [comment]
Now get the same parameters (PIXSCALE, CRPIX, CDELT) from FPoffsets.acam_params and do the same arithmetic

If binning is not the same, leave PIXSCALE blank

**Comment by astronomerdave** [comment]
implemented in commit 7d38ae307c233b8d98ead0da8f1c9b564080d507
