### ISSUE TITLE
Timeline plot is missing data on completed targets

### ISSUE THREAD

**Issue by chazshapiro** [CaltechOpticalObservatories/NGPS#21]
Currently the GUIs only visualize the OTM output, which is for upcoming targets only.  So as the night progresses, the timeline shrinks.  GUIs should also use the database/logs to include completed targets on the same plot.

**Comment by jenniferwillow** [comment]
Question?  Is the completed targets table being populated with all the information?  Wouldn't it be possible for the OTM to query completed targets?  What happens now is the GUI creates the input for running the OTM, runs it and then reads and plots the file.  If some of the targets have been observed should the OTM search the database so the completed targets are added to the output?

**Comment by chazshapiro** [comment]
How do you query completed targets - command line?

The OTM output CSV file is used for both plotting and populating the GUI tables.  If the CSV contains both completed and upcoming targets, how do you distinguish between them?

**Comment by jenniferwillow** [comment]
Hi Chaz,
     We probably need to talk this out. At the moment the system reruns the complete target list every time the OTM is run.  It doesn’t discriminate between active/inactive or pending vs. completed.  I update the colors of the row or plot based on the pending/acitve/completed flag in the table.  So the scenario that you described with the list getting shorter as the night goes on it not what the current behavior is.
     If targets have been completed and the completed observations table has been populated, I could query the database and fill in the additional information for the OTM as a pass through.
     Well, we should discuss this after our demo practice this afternoon.
Sincerely,
Jennifer
On May 24, 2023, at 10:56 AM, Chaz Shapiro ***@***.******@***.***>> wrote:



How do you query completed targets - command line?

The OTM output CSV file is used for both plotting and populating the GUI tables. If the CSV contains both completed and upcoming targets, how do you distinguish between them?

**Comment by chazshapiro** [comment]
So the plot needs the start time, end time, and start/end airmass of each observation.  I don't think the OTM is a good vehicle for compiling this information.  GUI should get the future targets from the OTM and the past targets from the database - @astronomerdave and @jenniferwillow should work this out.

**Comment by chazshapiro** [comment]
java gui only
