### ISSUE TITLE
startup display condition of slicecam GUI

### ISSUE THREAD

**Issue by astronomerdave** [CaltechOpticalObservatories/NGPS#215]
on start-up of slicecam I see this:
![image](https://github.com/user-attachments/assets/40084520-8759-40ab-a5a2-7cd4a284ec8a)

clicking "sync display" changes it to this:
![image](https://github.com/user-attachments/assets/ddcf7b61-6ce3-4d20-8682-952ce9759eaa)

this doesn't look like what's expected (size of images and placement of text)

**Comment by chazshapiro** [comment]
I think text is fixed but the zoom will always need a "sync display" whenever the binning changes
