### ISSUE TITLE
Twilight

### ISSUE THREAD

**Issue by astronomerdave** [CaltechOpticalObservatories/NGPS#22]
"Twilight" button should be highlighted only when Auto is not selected, and greyed-out otherwise, but Twilight is always clickable regardless of the state of Auto.

Also, Twilight should auto-fill the time/date fields,

![image](https://github.com/CaltechOpticalObservatories/NGPS/assets/3028392/fdb1a998-c64e-4105-a8de-1225811da735)

but instead opens a popup window (?), which appears to be cut off in the middle of a text field,

![image](https://github.com/CaltechOpticalObservatories/NGPS/assets/3028392/6f03be23-06d2-444a-a1a1-51077aa97a23)

**Comment by chazshapiro** [comment]
Fixed what the button does.  I will add the AUTO buttons as a separate issue
