### ISSUE TITLE
another slicecam header update

### ISSUE THREAD

**Issue by astronomerdave** [CaltechOpticalObservatories/NGPS#225]
In the SCAM headers, we need to add a term to CRPIX1 according to SLITW:
L:  +SLITW/PIXSCALE
R:  - SLITW/PIXSCALE
where PIXSCALE has already accounted for binning

**Comment by chazshapiro** [comment]
We might be missing a factor of 2 or 3 here (or both, maybe 3/2).  Start with 

L: +1.5*SLITW/PIXSCALE
R: -1.5*SLITW/PIXSCALE

**Comment by astronomerdave** [comment]
done, needs to be tested

**Comment by chazshapiro** [comment]
CRPIX1 only on both L and R, not CRPIX2

**Comment by astronomerdave** [comment]
> CRPIX1 only on both L and R, not CRPIX2
> 
> I tweaked slicecam_interface.cpp

I didn't catch that before committing.
commit dda27d33098c3d3f624909dae80aaf69bc3937fc fixes typo
