### ISSUE TITLE
"ETC Calculated" labels in Plan tab should be removed

### ISSUE THREAD

**Issue by chazshapiro** [CaltechOpticalObservatories/NGPS#23]
Parameter names should match the gray column headers of the target table table.

These do not always use the ETC.

**Comment by jenniferwillow** [comment]
Done. Is this what you had in mind?
<img width="275" alt="image" src="https://github.com/CaltechOpticalObservatories/NGPS/assets/21295144/a54d8692-132f-472d-9807-bf7f361837b5">

**Comment by chazshapiro** [comment]
Better, but we may want to show units
