### ISSUE TITLE
Guide on/off

### ISSUE THREAD

**Issue by astronomerdave** [CaltechOpticalObservatories/NGPS#236]
Currently, clicking the "Guide" button will turn on guiding but there is no way to turn it off.

Rather than YAB (Yet Another Button), consider making it a toggle: If guiding is off, then clicking Guide will turn it on.. If guiding is on, then clicking Guide will turn it off.

**Comment by chazshapiro** [comment]
There's a STOP button to the right of the GUIDE button.

DS9 has no parameter memory, so it is difficult to script different behaviors for 1 button depending on state (on the DS9 end).

**Comment by chazshapiro** [comment]
Rather, the button action could be a toggle that checks the guider state and requests the opposite, but the button would say "TOGGLE".  It is hard to script a different look/text for the button depending on the state.

**Comment by chazshapiro** [comment]
Closing this in the interest of housekeeping.  If people don't like the STOP button, resubmit.
