### ISSUE TITLE
Add slit offset feature for calibration

### ISSUE THREAD

**Issue by chazshapiro** [CaltechOpticalObservatories/NGPS#238]
This will be extremely helpful for calibration.  It seems we already have the slitd commands, we just need new internal parameters cf. Matt.

The CRPIX1 headers in SCAMs will need an extra term.  The L and R cams will have opposite signs for this term -- you have a 50% of getting it right:

± OFFSET_IN_ARCSEC / PIXSCALE

which would be inside the parentheses before binning factors are applied, i.e. add to the value taken from FPoffsets.  **This is for CRPIX1 only, not CRPIX2**

I'll put a command in the SCAM GUI menu (not a button).

**Comment by chazshapiro** [comment]
This is working although it seemed to demonstrate that we don't have the correct slit scale in arcsec/mm.  This is a calibration issue, so I'm closing it as a software issue.

**Comment by astronomerdave** [comment]
commit 01857e2f2f17cc93ff01fcc0389691a3dadc0e60
