### ISSUE TITLE
Fans need to power on when rack is plugged in.

### ISSUE THREAD

**Issue by MateuszKM** [CaltechOpticalObservatories/NGPS#241]
NPS 2-8 needs to be configured to turn on during NPS2 power-up sequence.

**Comment by astronomerdave** [comment]
already is

**Comment by MateuszKM** [comment]
I had to manually turn on the fans yesterday.

**Comment by astronomerdave** [comment]
I see the problem now; we're both right. The plug for the fan is set to come on by default. The problem seems to be that the fan is not plugged in where it's supposed to be (in other words, it has been moved).
I've now changed the plug assignments on the NPS units.
