### ISSUE TITLE
End of night script vs. shutdown

### ISSUE THREAD

**Issue by MateuszKM** [CaltechOpticalObservatories/NGPS#242]
Found instrument cover open this morning (12/12 PST). Consider an end of night script that closes covers, turns off lamps, turns off detectors (anything else?)
In daytime stat it should be possible to open poll the motor positions for the acam without trying to open acam camera.

**Comment by astronomerdave** [comment]
We already have a nightly shutdown script (oddly enough, it's called `nightlyshutdown` -- it's in the developer's path), and it was run last night. I will have to look into why it didn't close the cover. Ultimately, this is going to be a button on the GUI with the process performed by the Sequencer, but for now we are using the script. (The Sequencer's currrent shutdown process shuts down _everything_, which isn't needed to be done nightly.)

Also, day or night it is already possible to open acam motors without opening the camera. The command-line command for that is `acam open motion`. This is in contrast to `acam open camera`, which opens only the camera, or `acam open`, which opens both. See also `acam help`.
