### ISSUE TITLE
copy/insert copies the selection state

### ISSUE THREAD

**Issue by astronomerdave** [CaltechOpticalObservatories/NGPS#26]
If you right-click-copy a selected row, then right-click-insert-copied-row, then the selection state is copied and pasted and remains set forever. I.E. all rows are yellow as if all rows are selected. There is then no way to de-select a row. All remain yellow no matter which is clicked on.

![image](https://github.com/CaltechOpticalObservatories/NGPS/assets/3028392/c33fcc76-c57a-420f-9b52-9bcf967c2720)

![image](https://github.com/CaltechOpticalObservatories/NGPS/assets/3028392/a3040fa7-1c30-4ae0-a3c4-30f509fd26ea)

As an aside, what's going on with the DEC col there, that has "..." in some rows and full numbers in the one which is selected?

**Comment by jenniferwillow** [comment]
(1) I’m unable to reproduce this with the current build.  I can’t get more than one line selected.
(2) The column is narrower than the text so you see a …
Jennifer

On May 24, 2023, at 4:00 PM, David Hale ***@***.******@***.***>> wrote:



If you right-click-copy a selected row, then right-click-insert-copied-row, then the selection state is copied and pasted and remains set forever. I.E. all rows are yellow as if all rows are selected. There is then no way to de-select a row. All remain yellow no matter which is clicked on.

[image]<https://user-images.githubusercontent.com/3028392/240758589-c33fcc76-c57a-420f-9b52-9bcf967c2720.png>

[image]<https://user-images.githubusercontent.com/3028392/240758862-a3040fa7-1c30-4ae0-a3c4-30f509fd26ea.png>

As an aside, what's going on with the DEC col there, that has "..." in some rows and full numbers in the one which is selected?

**Comment by astronomerdave** [comment]
I can reproduce it with this particular target list (**Dave Test**) but only with this target list, so perhaps there is something corrupted in the file, so will close this issue.
