### ISSUE TITLE
implement status messages

### ISSUE THREAD

**Issue by astronomerdave** [CaltechOpticalObservatories/NGPS#27]
The Messages window only displays somewhat cryptic, short text like "start" ACK "do one" ACK, etc. but should display human-friendly messages to tell the user what is going on. A perfect example where this can be important is shown here,

![image](https://github.com/CaltechOpticalObservatories/NGPS/assets/3028392/36c4fa3f-446c-436d-9ae3-289274d18a23)

where the user clicked "GO" but nothing happened. Only because I had the listener window running (in yellow) could I see the cause of the error (all NOTICE: messages should probably be displayed in Messages).

**Comment by astronomerdave** [comment]
Understood.
I suggest start with the following :

1. mine the broadcast messages for the tag **NOTICE:** and add that text (after the tag) to the Messages; I think anything tagged with **NOTICE:** is useful to display verbatim. And if you can color code (seems like you can since I see blue and black) then color anything that contains the string "ERROR" as red.
2. mine broadcast messages for state changes and display things like, "waiting for <xxx>" and then remove that message when no longer waiting (e.g. _waiting for slit_, _waiting for flexure_, etc.) If you can't remove messages then I'm not sure, maybe don't say "_waiting for..._"  because that could lead to confusion if it always says _waiting..._.

**Comment by chazshapiro** [comment]
The message pane displays broadcast messages starting with ERROR or NOTICE.  GUICLEAR will clear the pane.

I don't think the GUI is the right place to track the state of the OS for the "waiting for" items.  We could use NOTICE or another tag to display these.  The OS knows what it's waiting for so it could just clear the pane and send the most up-to-date list of waiting items.  This however would also remove ERRORs and other messages.  If we want to avoid that, we could add a second pane just for "waiting for".

**Comment by chazshapiro** [comment]
java issue only
