### ISSUE TITLE
Define CSV format

### ISSUE THREAD

**Issue by astronomerdave** [CaltechOpticalObservatories/NGPS#28]
Define the format of the CSV file so that users can generate a raw CSV file.
Documentation should include the minimum set.

**Comment by chazshapiro** [comment]
This is defined in section 3.2 of the OTM/ETC manual

https://caltech.sharepoint.com/:w:/r/sites/coo/ngps/_layouts/15/Doc.aspx?sourcedoc=%7BC22CFB96-718A-4980-B167-B5218F2DA535%7D&file=NGPS-manual-OTM-ETC.docx&action=default&mobileredirect=true
