### ISSUE TITLE
OTMflag too long for column width

### ISSUE THREAD

**Issue by astronomerdave** [CaltechOpticalObservatories/NGPS#29]
suggest adjusting flag text to fit column, or adjust column width to fit text

**Comment by chazshapiro** [comment]
The (short) flags are defined in the manual, so we can just use the flag string

**Comment by astronomerdave** [comment]
@chazshapiro ETC SRCMODEL parameters are also quite long, too long for the display. Maybe that's just the way it has to be? Or could we do better? Could the options be pull-down-selectable (or are there too many possible combinations)?

**Comment by chazshapiro** [comment]
There are too many options (and growing)

From: David Hale ***@***.***>
Reply-To: CaltechOpticalObservatories/NGPS ***@***.***>
Date: Thursday, May 25, 2023 at 10:54 AM
To: CaltechOpticalObservatories/NGPS ***@***.***>
Cc: "Shapiro, Charles A (US 389E)" ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [CaltechOpticalObservatories/NGPS] OTMflag too long for column width (Issue #29)


@chazshapiro<https://urldefense.us/v3/__https:/github.com/chazshapiro__;!!PvBDto6Hs4WbVuu7!IlpsHfbZSIOfgVDZwy6nlaFoVZVFCMouhluMwK9BLMADUsnS_HJHpAjcjAcsMAg73wOu6mXlVhS2hsHZSe3pwEFAPdIjNwfzUds$> ETC SRCMODEL parameters are also quite long, too long for the display. Maybe that's just the way it has to be? Or could we do better? Could the options be pull-down-selectable (or are there too many possible combinations)?

**Comment by astronomerdave** [comment]
OK, SRCMODEL params are one thing, especially since they are editable, but I think we do need error messages (OTMflag) to be fully readable.

**Comment by jenniferwillow** [comment]
The flags are passed from the OTM and I have no ability to truncate them arbitrarily.  I think this is an OTM issue.  The GUI simply displays the text that comes in.  I'm going to close this as a GUI issue and refer it to Chaz.

**Comment by chazshapiro** [comment]
We saw a message in OTMflag that was something like "Target is being observed during the day".  Where is that coming from?

**Comment by chazshapiro** [comment]
![Screenshot 2023-06-01 at 3 21 53 PM](https://github.com/CaltechOpticalObservatories/NGPS/assets/9029957/53fb74c6-7648-4be1-8fa2-2d961330954e)

**Comment by jenniferwillow** [comment]
Hi Chaz,
     I was mistaken when I thought this was coming from the OTM.  The actual text is in the table code that transforms the original text into the longer string.  Here’s the code:

        if(row == 11){
            java.lang.String flag = current.otm.getOTMflag();
            if(flag.contains("ALT")){
               returnObject = "Target's altitude is out of range" ;
            }else if(flag.contains("AIR")){
                returnObject = "Target's airmass is out of range" ;
            }else if(flag.contains("HA")){
                returnObject = "Target's hour angle is out of range" ;
            }else if(flag.contains("DAY")){
                returnObject = "Obervation is happening during daylight" ;
            }else{
                returnObject = current.otm.getOTMflag();
            }
//           returnObject = current.otm.getOTMflag();
        }

Do you want me to replace the text with the abbreviations?  I can do this easily.
Sincerely,
Jennifer

On Jun 1, 2023, at 3:22 PM, Chaz Shapiro ***@***.******@***.***>> wrote:



[Screenshot 2023-06-01 at 3 21 53 PM]<https://user-images.githubusercontent.com/9029957/242740721-53fb74c6-7648-4be1-8fa2-2d961330954e.png>

**Comment by chazshapiro** [comment]
Let's just use whatever the OtM puts in the OTMflag output field.

**Comment by jenniferwillow** [comment]
I have changed the text to make it shorter and now it's no longer truncating.  I think this issue is closed.
