### ISSUE TITLE
Plot is in minutes, should be in UTC

### ISSUE THREAD

**Issue by astronomerdave** [CaltechOpticalObservatories/NGPS#32]
Kastav says actual time is important.

**Comment by chazshapiro** [comment]
Fixed by @JHauss-JPL .  Probably needs some tweaking (font etc.) - I'll handle that. 
<img width="1227" alt="Screenshot 2024-09-08 at 11 38 07 AM" src="https://github.com/user-attachments/assets/7b3b5eb7-bc92-4671-aa1a-f63caec0b3ad">
