### ISSUE TITLE
Drop EPOCH column in GUI, CSV, database, etc.

### ISSUE THREAD

**Issue by chazshapiro** [CaltechOpticalObservatories/NGPS#36]
Cf.  https://github.com/CaltechOpticalObservatories/NGPS/issues/17

...we do not need the EPOCH field as we will require all coordinates to be given in ICRS or FK5/J2000.  Documentation needs to make this clear.  Keeping the field may be confusing since we won't be using it for anything.  It would be nice to have the documentation include a link to some convenient conversion tool, but I haven't found one besides Astropy.

Coordinates sent to the TCS should specify J2000 always without needing an input.

If we want to just hide this field i.e. leave it in the database but not display it anywhere, that may be OK, but it should not be a required column in an imported CSV file.

**Comment by chazshapiro** [comment]
OTM has been updated to not require an "epoch" column in the CSV.  OTM will just ignore it if present.

**Comment by astronomerdave** [comment]
All references to and uses of EPOCH have been removed from the Sequencer and from the documentation (NGPS.ICS.TEC.001.docx).
After @jenniferwillow removes it from DB and GUI, this issue should be completed.
