### ISSUE TITLE
Twilight in Timeline Plot and OTM

### ISSUE THREAD

**Issue by cfremling** [CaltechOpticalObservatories/NGPS#38]
There can be a discrepancy between the twilight times (dashed line) in the timeline plot and what the OTM seems to be using. I cannot fit any more observations into the night in the attached figure even though the Timeline figure seems to show that there is ample space at the end of the night. There are no clear flags visible in the OTM panel for targets that cannot be observed
<img width="1622" alt="twilight_otm_discrepancy" src="https://github.com/CaltechOpticalObservatories/NGPS/assets/4759961/59392387-50f1-4cd8-a521-e7c94c71edb1">

**Comment by chazshapiro** [comment]
The OTM currently defines twilight as the sun altitude at -12 deg. It won't allow observations if the sun is above that. What's the GUI definition?

**Comment by chazshapiro** [comment]
The OTM also prints its predictions for twilights - check the message pane.

**Comment by jenniferwillow** [comment]
I'm using JSkyCalc to calculate evening and morning twilight.  It defines twilight as -18 degrees.
