### ISSUE TITLE
Automate geometry re-calibration using ACAM images

### ISSUE THREAD

**Issue by chazshapiro** [CaltechOpticalObservatories/NGPS#41]
The default offsets on the P200 TCS periodically (nightly? after resets?) need to be calibrated and "zeroed".  We should be able to do this using the ACAM.  There needs to be an automatic (or very easy + documented) procedure for doing so.

Steps:
1. Choose target to center on ACAM (have a list of good targets) -- use POINTMODE = ACAM
~~2. Use FPoffsets to solve for scope coordinates (acam to scope) -- same as when doing this for a target from the list~~
3. Slew to target -- should be visible in ACAM but not centered.
4. Do acquisition sequence with offset upper limit removed
5. Once target is acquired, the resulting offsets should be logged, ~~then zeroed out in the TCS.~~ then verbally signal the TCS operator to zero the offsets.
6. Repeat acquisition to verify offset is near 0; might as well log and zero the offsets again.
7. Reinstate offset upper limit

If the required offsets are very large (several arcmin) the acquisition may fail.  Then we need some manual procedure involving e.g. astrometry.net for step 4-5.

**UPDATED:** step 4 -- We will not be allowed to automate zeroing the offsets, the TCS operator will have to do that

**Comment by chazshapiro** [comment]
If a target field is solved during acquisition but with a large offset, this effectively accomplishes the above, except we normally prevent large offsets.  We could have some exception to the rule or put a warning in the text box that uses the last solution to zero the offsets.

**Comment by jenniferwillow** [comment]
Hi Dave, Chaz
     I’m a little unclear about what you mean by zero the offsets.  There is an offset parameter (actually RA and Dec offset) maintained by the telescope and there is a command to zero this offset.  Is this what you mean or is this a calibration procedure for the FPoffsets code?  It sounds like you’re talking about the z offsets command.
     How would you want to implement this calibration function?  Do you want a button on the GUI that runs the calibration?  Should we create a script that can be run to accomplish this?  I’m open to suggestions.
Sincerely,
Jennifer Milburn


On Jul 1, 2023, at 11:31 AM, Chaz Shapiro ***@***.******@***.***>> wrote:



The default offsets on the P200 TCS periodically (nightly? after resets?) need to be calibrated and "zeroed". We should be able to do this using the ACAM. There needs to be an automatic (or very easy + documented) procedure for doing so.

Steps:

  1.  Choose target to center on ACAM (have a list of good targets)
  2.  Use FPoffsets to solve for scope coordinates (acam to scope) -- same as when doing this for a target from the list
  3.  Slew to scope coordinates -- target should be visible in ACAM but not centered.
  4.  Do acquisition sequence with offset upper limit removed
  5.  Once target is acquired, the resulting offsets should be logged, then zeroed out in the TCS.
  6.  Repeat acquisition to verify offset is ~0; might as well log and zero the offsets again.
  7.  Reinstate offset upper limit

If the required offsets are very large (several arcmin) the acquisition may fail. Then we need some manual procedure involving e.g. astrometry.net<http://astrometry.net> for step 4-5.

**Comment by jenniferwillow** [comment]
Hi Dave, Chaz

     I had another thought.  It looks like this procedure is identical to acquiring a target except that the upper limit on the offsets are removed.  Maybe we just put the system into “calibration” mode (and make this a command that can be sent by the OS).  On considering this again, all of the telescope motion commands are sent by the OS so I’m not sure how this should be assigned to the ACAM system?  I think this is really a procedure that needs to be implemented in the OS and not part of ACAM.  None of the actions in this list are really actions for the ACAM beyond supporting the functions that it already does (i.e. acquire images and return the file name).
Sincerely,
Jennifer Milburn


On Sep 14, 2023, at 10:33 AM, Chaz Shapiro ***@***.******@***.***>> wrote:



If a target field is solved during acquisition but with a large offset, this effectively accomplishes the above, except we normally prevent large offsets. We could have some exception to the rule or put a warning in the text box that uses the last solution to zero the offsets.

**Comment by astronomerdave** [comment]
The "X" command is indicated in the manual as being _DISABLED-- not available to clients; telescope operator only_.  We may have to resort to only logging the offsets in step #4, then give a verbal signal to the TCS operator to perform the zeroing.

**Comment by jenniferwillow** [comment]
You might want to look at the TX command which is available remotely.
Jennifer
Sent from my iPad

On Aug 26, 2024, at 10:25 PM, David Hale ***@***.***> wrote:

﻿

The "X" command is indicated in the manual as being DISABLED-- not available to clients; telescope operator only. We may have to resort to only logging the offsets in step #4<https://github.com/CaltechOpticalObservatories/NGPS/issues/4>, then give a verbal signal to the TCS operator to perform the zeroing.

**Comment by astronomerdave** [comment]
John Henning reported today that client access to X and TX have been disabled as a policy decision. Before I ask to open those up to NGPS, I'd like for us to come up with a design plan and procedure for exactly how this calibration would be carried out.

**Comment by astronomerdave** [comment]
Updated original issue because Rick Burruss has now said that the X command will not be made available to us.

**Comment by chazshapiro** [comment]
But can't the operator do it?  The offset has to be zeroed by someone.

**Comment by chazshapiro** [comment]
I guess we can automate by carrying "de-offset" parameters ourselves. Rather than zero it on the TCS, we record the values that would have been zeroed and save them somewhere like sequencerd or tcsd. Then we have to apply them to every TCS query.

**Comment by astronomerdave** [comment]
> But can't the operator do it? The offset has to be zeroed by someone.

yes, of course, but humans aren't easily scriptable. I updated the original issue again.

**Comment by chazshapiro** [comment]
Alternate script for doing this:

1. **Ask operator** to slew to anywhere with a decent amount of stars.  Perhaps have a list of options available for the operator.
2. Press button on GUIDER GUI --> 
    2a. Get TCS coords, convert to ACAM coords.  Set these ACAM coords as the goal.
    2b. Do ACAM acquisition using this goal with offset limit removed.
    2c. Display final offsets and solver result.  Log these.
3. Assuming solver script returns GOOD, **ask operator** to zero out the current offsets.
4. **Ask operator** to slew off target and slew back.
5. Press same button on GUIDER GUI --> Confirm final offsets are small.

**Comment by astronomerdave** [comment]
@chazshapiro should I be implementing the steps in the [original (edited) first post](https://github.com/CaltechOpticalObservatories/NGPS/issues/41#issue-1784139395) or the "[alternate script" above](https://github.com/CaltechOpticalObservatories/NGPS/issues/41#issuecomment-2315810586)? The former seems to be initiated from the main observe GUI while the latter is initiated from the ACAM GUI. If the former then is it your expectation that a key in the target name (such as `_TCSOFFCAL`) would trigger it?

**Comment by chazshapiro** [comment]
I like the Alternate version better - ACAM GUI only

**Comment by astronomerdave** [comment]
Okay then how about I add a command to acamd that you can tie to a button? I'll call the command `offsetcal`, it will take no arguments, and carry out the steps 2a,b. I'm not sure how to trigger 2c.

**Comment by chazshapiro** [comment]
Sounds good.  For 2c, start by generating this output.  Then we'll push it to the ACAM GUI.

```
ACAM CALIBRATION RESULT

Astrometry result = ________   // GOOD, NOISY, etc.
ACAM center = ____, _____      // RA, DEC from solver

Offset RA  = ________ ''    // reqstat
Offset DEC = ________ ''    // reqstat
Total Offset = _________ '' // hypotenuse

Total Offset GOAL = <TBD>

If the total offset is larger than the goal, ask the operator to zero them now.  Then slew off the target, slew back, and press CALIBRATE again to verify offsets are still small.

Calibrating and zeroing the offset improves the efficiency of the Acquisition and Guide system but does not affect accuracy.
```

**Comment by chazshapiro** [comment]
Actually, if `acam offsetcal` returns the message to STDOUT, that might be good enough -- try that first, see if it shows up in DS9

**Comment by chazshapiro** [comment]
We have a bit of a chicken and egg problem here.  The CALIBRATE button on the ACAM GUI requires that the geometric model be correct so it can zero the TCS offsets.  We have a geometric-model-corrector option on the astrometry solver now that requires that the TCS offset be zero.  If we manually use a bright star to zero the offsets, we can correct the model.  Then if the model is stable, people can just use the CALIBRATE button every so often to remove offsets.  But if the model is not stable for some reason, then people will need to repeat the manual offset zeroing to update the model before CALIBRATE works.

**Comment by chazshapiro** [comment]
Changed the title to reflect the fact that this is part of a larger calibration issue.  Not only do we have to get the correct TCS offset, but we have to account for changes in the center of rotation when the instrument is re-mounted.

**Comment by chazshapiro** [comment]
I believe I've got the correct procedure here.  The assumption is that the instrument is rigid, so once we've measured geometry between ACAM, SCAM and the slit, these never change.  The only things changing when we re-mount the instrument are the center of rotation (CoR), Theta0 (slit angle relative to CASS angle), and some random TCS offset.

0. Start with well-calibrated model, i.e. ACAM/SCAM/slit are known relative to each other and some nominal (old) CoR.
1. Slew to a dense field, take an ACAM image.  Solve to get the coordinates "ACAM_1".
2. With the existing (old) model, use ACAM_1 to guess the CoR "G_1" .
3. Rotate the CASS by 90 deg;  Solve to get coordinates ACAM_2.
4. With the existing model, use ACAM_2 to guess the CoR "G_2".  
5. Also compute the slit position S_2 and orientation PS_2 - this is accurate because relative ACAM-SLIT orientations don't change.
6. Use G_1 and G_2 to triangulate the true CoR "C"
7. Offset the TCS to C and zero the offsets
8. Compute Theta0 = PS_2 - CASS_2
9. Use my "model tweaker" which adjusts the relative ACAM-CoR parameters so that ACAM now predicts C.
10. With C, S_2, and PS_2 known, adjust the model SLIT-CoR parameters.

With the model now updated, we should be able to predict the ACAM and SLIT from the TCS coordinates, which are registered to the CoR.

**Comment by chazshapiro** [comment]
Continuing to jot my thoughts here...

The ACAM should always be able to predict the SLIT coordinates if the instrument is rigid.  So, with a solved ACAM field, the FPOffsets(ACAM<-->SLIT) should always be accurate.  What is variable is the location of the Center of Rotation and the random TCS errors or offsets.  These affect our ability to slew the target directly to the slit.  However, the TCS info and control is not perfect, even for small moves, i.e. we never expect to be able to get the target perfectly on the slit using the TCS as a reference.

We also know that the CoR is usually pretty close to the slit but not perfectly on it.  Thus if we register the TCS to the slit then rotate the CASS ring, the TCS and slit coordinates will no longer align.  However, the TCS "guess" should still be well within the SCAM field of view.  Thus, as long as the TCS errors are small, slewing the TCS to a target should put it in decent range of the slit, **which should be our only goal for a slew**.  It will then **always** require manual or guider adjustment.  We just prefer that adjustment to be small.

So I think the upshot is now that the model is pretty well calibrated, we don't need the CoR to find things anymore.  I should re-write the model in FPoffsets to relate the ACAM and SLIT directly (with CASS angle!).  Then I add a function to tweak the model based on registering a target (with very accurate coordinates) on the slit while solving the ACAM field.  Then users will simply want to register the TCS to the slit, which will make slews as accurate as the TCS, plus a few arcsec error due to the CoR, which we can live with.

Finally, FPOffsets(X<-->SCOPE) calculations would be unnecessary.  We can replace SCOPE everywhere with SLIT, knowing that there is some unavoidable error here that will affect slews but not the endpoint of acquisition.  The Python can be changed to make SCOPE and SLIT the same without acamd having to care about that.  Eventually acamd should be simplified to remove references to SCOPE.

**Comment by chazshapiro** [comment]
@astronomerdave We need an acamd CL command that just runs FPoffsets.load_calibration()

**Comment by chazshapiro** [comment]
To be clear, the Python function FPoffsets.load_calibration() will have no args and will return a bool.  The CL command also has no args and could return the same bool.  The bool will indicate the success/fail of loading the calibration.

**Comment by chazshapiro** [comment]
This is ready for testing on sky.

**Comment by chazshapiro** [comment]
Assuming the alpha version of this works, we need to decide what the UI for this capability should be.

**Comment by chazshapiro** [comment]
This worked!  Closing it as a priority software issue, now we need to use it for calibration.
