### ISSUE TITLE
Problem loading CSV file into GUI

### ISSUE THREAD

**Issue by chazshapiro** [CaltechOpticalObservatories/NGPS#43]
In NGPS-OBSERVE I am trying to import

/home/developer/Software/Python/OTM/inputCSV/sample_input_3.csv

but it is not being fully parsed.  Many rows are missing, including first few.  Is this not a valid CSV format for the GUI?

<img width="642" alt="Screenshot 2023-09-25 at 10 02 17 AM" src="https://github.com/CaltechOpticalObservatories/NGPS/assets/9029957/5a167f6c-9b3c-467e-99be-c249cf5aa1b0">

**Comment by jenniferwillow** [comment]
Hi Chaz,
    No resolution yet but I am looking at the problem now.  I just wanted you to know I’m working on it.
Sincerely,
Jennifer

On Sep 25, 2023, at 10:01 AM, Chaz Shapiro ***@***.******@***.***>> wrote:



Assigned #43<https://github.com/CaltechOpticalObservatories/NGPS/issues/43> to @jenniferwillow<https://github.com/jenniferwillow>.

**Comment by jenniferwillow** [comment]
Hi Chaz,
      The issue has been resolved.  It turned out to be a vector index problem that got introduced to the code when I added the requested slit angle to the table (or changed its position).  I have tested each of the 4 CSV files and all of them import without issue.  I also found that the first time the OTM was run it got passed a 0.0 for the airmass limit and that caused an error.  I've corrected both issues and I have deployed a new version.  No change on your part to run the new code.
Sincerely,
Jennifer

**Comment by jenniferwillow** [comment]
Hi Chaz,
     I also deployed a
