### ISSUE TITLE
Once a target has a coordinate entered in the GUI, the coordinate can never again be removed.

### ISSUE THREAD

**Issue by astronomerdave** [CaltechOpticalObservatories/NGPS#44]
Coordinates (RA, DEC) should be allowed to be empty, and a target with empty coordinates _can_ be created. But, if you enter coordinates, then you can not change your mind and later erase them.

Doing so prints:
_java.lang.RuntimeException: Expected a string of the form hh:mm:ss.sss, but got: ''_
in the console window. Although interestingly, there is no such exception if you get the form "wrong", as long as it's a number. I.E., entering "1" or "1.0" or "0:0" all are accepted without error.

**Comment by jenniferwillow** [comment]
I will look at this when I return next week.
Sincerely
Jennifer

Sent from my iPad

On Oct 11, 2023, at 1:01 PM, David Hale ***@***.***> wrote:

﻿

Coordinates (RA, DEC) should be allowed to be empty, and a target with empty coordinates can be created. But, if you enter coordinates, then you can not change your mind and later erase them.

Doing so prints:
java.lang.RuntimeException: Expected a string of the form hh:mm:ss.sss, but got: ''
in the console window. Although interestingly, there is no such exception if you get the form "wrong", as long as it's a number. I.E., entering "1" or "1.0" or "0:0" all are accepted without error.

**Comment by chazshapiro** [comment]
I was just able to edit the target list to replace one RA with a blank, but when I clicked ACCEPT the entire list disappeared.

**Comment by astronomerdave** [comment]
Not currently reproducible.
