### ISSUE TITLE
GUI Edit menu items are mostly non-functional

### ISSUE THREAD

**Issue by chazshapiro** [CaltechOpticalObservatories/NGPS#64]
![Screenshot 2024-07-12 at 2 15 43 PM](https://github.com/user-attachments/assets/97b58acd-dccc-4c40-9cc5-55401c28664d)

"Get Target from Database" is the only one that appears to do anything

**Comment by astronomerdave** [comment]
Shouldn't these do the same thing as the right-click-popup menu?

**Comment by chazshapiro** [comment]
yup

**Comment by chazshapiro** [comment]
The top Edit menu and the target table are in 2 different scopes and I don't understand how to get to one from the other.

**Comment by chazshapiro** [comment]
mostly fixed -- remaining bugs are minor and will be moved to a new issue
