### ISSUE TITLE
Can't select multiple rows in GUI main table

### ISSUE THREAD

**Issue by chazshapiro** [CaltechOpticalObservatories/NGPS#75]
Like the title says, you can't select multiple rows in the GUI main table.  I'm trying SHIFT, CTRL, ALT.  Dragging the cursor just drags the selected row.

Was this ever working?  I vaguely recall having this capability, but I've just been debugging the Copy/Paste features and they seem designed for single rows.

**Comment by chazshapiro** [comment]
In class NGPSFrame, we have:

```
private int selected_table_row;
private int[] selected_table_rows;
```
where the latter is never used.

**Comment by JHauss-JPL** [comment]
Are you looking to be able to select multiple rows?  The detail pane on the right is populated from the selected row and you also have the ability to drag and drop the selected row anywhere in the table.  What would you like to be able to do with multiple rows selected?

**Comment by chazshapiro** [comment]
NB. I've committed a lot of changes I haven't pushed yet. I'll do that ASAP. 

We're supposed to be able to use items in the Edit menu or the right–click menu on multiple rows.

I didn't mark this issue as a Priority because it's not crucial.

**Comment by astronomerdave** [comment]
I think the primary motivation was for deleting a block of rows, possibly also moving a block of rows. If you needed to move (or remove) a large number of rows then it seemed tedious to select the row, menu, delete, select, delete, etc.

One thing that might not be immediately obvious is that, if you want to take 10 exposures of the same target you have to have 10 copies of that row -- each row represents a single exposure. It could be then, that moving or removing a single target could involve manipulating a large number of rows, one.at.a.time.

**Comment by chazshapiro** [comment]
JM may have disabled this while debugging other things

**Comment by chazshapiro** [comment]
java issue only
