### ISSUE TITLE
save changes buttons should be greyed

### ISSUE THREAD

**Issue by astronomerdave** [CaltechOpticalObservatories/NGPS#9]
Currently always illuminated/colored, should be greyed-out when not applicable per design document. Also should be called "save changes" rather than "accept cancel". ![image](https://github.com/CaltechOpticalObservatories/NGPS/assets/3028392/3d831c1d-10a2-4b95-9cdd-b05aca500d17)

**Comment by jenniferwillow** [comment]
I implemented this as GREEN when no edit has been done and ORANGE when the table needs to be recalculated.  Tell me if you want to change the GREEN icon to grey.  I'm closing this now and waiting for instructions.
