### ISSUE TITLE
GUI should remind user to shutdown on quit

### ISSUE THREAD

**Issue by chazshapiro** [CaltechOpticalObservatories/NGPS#94]
When clicking the Quit menu item,

- Always prompt "Are you sure?"
- If not currently in the OFFLINE state, then notify the user that they should (must?) shutdown first.

Can this also be applied to closing the GUI via the upper right "X"?

**Comment by astronomerdave** [comment]
Can the upper right "X" be removed, so there's only one way out?

**Comment by chazshapiro** [comment]
The "X" can be disabled so it doesn't do anything - is that enough?  Internet says you can't remove it without breaking other things.

**Comment by chazshapiro** [comment]
<img width="1301" alt="Screenshot 2024-08-20 at 9 22 10 AM" src="https://github.com/user-attachments/assets/e046d86b-481f-4061-a330-fc6ee99b85b0">

We can close this if we don't mind the useless  "X"

**Comment by astronomerdave** [comment]
This looks good. If the system is already in the shutdown state, can this message be different? (Maybe just the "are you sure?")
