### ISSUE TITLE
GUI - undoing deleted row is buggy

### ISSUE THREAD

**Issue by chazshapiro** [CaltechOpticalObservatories/NGPS#96]
To duplicate bug:

1. Load or create list with multiple rows
2. Click Accept
3. Delete a row
4. Click red Cancel button --> row reappears
5. Click Accept --> row is removed or modified

Also, the resulting OTM timeline and main table data do not match.

When duplicating, it's helpful to NOT use e.g. 5 copies of the same target so you can verify which are being lost or changed.

**Comment by jenniferwillow** [comment]
Hi Chaz,
     I think I found the problem. The delete stack wasn’t being reset when the Cancel action takes place.  The result was removing the any observations  that had been deleted even though you canceled the delete.  I think this solves the problem.  Sorry it’s taken so long to find the bug.
     Take a look when you get a chance and see if it works for you as well.
Sincerely,
Jennifer Milburn


On Aug 19, 2024, at 2:19 PM, Chaz Shapiro ***@***.******@***.***>> wrote:



To duplicate bug:

  1.  Load or create list with multiple rows
  2.  Click Accept
  3.  Delete a row
  4.  Click red Cancel button --> row reappears
  5.  Click Accept --> row is removed or modified

Also, the resulting OTM timeline and main table data do not match.
