### ISSUE TITLE
single broadcast message appears multiple times in GUI

### ISSUE THREAD

**Issue by astronomerdave** [CaltechOpticalObservatories/NGPS#99]
Getting the next target from the database generated a single broadcast message (inset yellow terminal) but the GUI messages panel displayed multiple lines, including a garbled line.
![image](https://github.com/user-attachments/assets/1fc2af48-42d6-4ac3-9bf5-61cf9c0d676f)

**Comment by chazshapiro** [comment]
Can't reproduce
